name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git python3-dev libffi-dev libssl-dev cmake openjdk-17-jdk zip unzip zlib1g-dev autoconf libtool pkg-config
          pip install --upgrade pip
          pip install "cython<3.0.0" buildozer

      - name: Build with Buildozer
        run: |
          # Создаем папки лицензий заранее
          mkdir -p /home/runner/.buildozer/android/platform/android-sdk/licenses
          echo -e "8933bad161af4178b1185d1a37fbf41ea5269c55\nd5624a996839a99227e5965bea033f5a77528159\n24333f8a63b6825ea9c5573f8435929d00fca03a" > /home/runner/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
          echo -e "84831b9409646a918e30573bab4c9c91346d8abd\n50466322461015d0865f3c2f458e1ecf422029b1" > /home/runner/.buildozer/android/platform/android-sdk/licenses/android-googletv-license
          
          # Основная сборка
          yes | buildozer android debug
        env:
          ACCEPT_SDK_LICENSE: "yes"
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Xmx2048m"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: WarehouseScanner-APK
          path: bin/*.apk
          
