name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git python3-dev libffi-dev libssl-dev cmake openjdk-17-jdk zip unzip zlib1g-dev autoconf libtool pkg-config
          pip install --upgrade pip
          pip install "cython<3.0.0" buildozer

      - name: Pre-configure Buildozer SDK
        run: |
          # Создаем структуру папок, которую ожидает Buildozer
          mkdir -p /home/runner/.buildozer/android/platform/android-sdk/build-tools/33.0.0
          # Копируем системный aidl в папку Buildozer
          cp $ANDROID_HOME/build-tools/33.0.0/aidl /home/runner/.buildozer/android/platform/android-sdk/build-tools/33.0.0/
          # Принимаем лицензии для этого пути
          yes | sdkmanager --sdk_root=/home/runner/.buildozer/android/platform/android-sdk --licenses || true

      - name: Build with Buildozer
        run: |
          # Запускаем сборку. Теперь Buildozer увидит aidl там, где искал.
          buildozer android debug
        env:
          ACCEPT_SDK_LICENSE: "yes"
          
